return data of children categories
mega-mall/mega-mall pull request #14
Opened 2020-11-19 22:43 UTC by DGjorgjievski

2020-11-20 21:56 UTC, andjiev requested changes

2020-11-20 21:56 UTC, andjiev commented on src/pages/product-list/components/display/display.tsx
> +  const getFilters = () => {
you already have everything that you need with the subCategoryItem :) just check if props.subcategoryItem.children && props.subcategoryItem.children.length > 0 then filter = props.subcategoryItem.title + props.subcategoryItem.children.map(x => \`&filter=${x.title}\`), else just return props.subcategoryItem.title

2020-11-20 22:28 UTC, DGjorgjievski commented on src/pages/product-list/components/display/display.tsx
> +  const getFilters = () => {
Will do ^_^

2020-11-21 00:54 UTC, andjiev submitted a review, later dismissed

2020-11-21 01:03 UTC, andjiev approved these changes

2020-11-21 03:02 UTC, merged